Transformed most functions into async functions
KygekTeam/KygekEatHeal pull request #2
Opened 2022-02-21 03:35 UTC by JavierLeon9966

2022-02-21 03:47 UTC, KygekDev commented on src/KygekTeam/KygekEatHeal/EatHeal.php
> +            $this->processTransaction($name, $price),
Syntax error

2022-02-21 04:09 UTC, JavierLeon9966 commented on src/KygekTeam/KygekEatHeal/EatHeal.php
> +            $this->processTransaction($name, $price),
Fixed

2022-02-21 04:12 UTC, KygekDev requested changes
There are about 20 lints, please fix them if possible:
https://poggit.pmmp.io/ci/KygekTeam/KygekEatHeal/~/pr:2

2022-02-21 04:43 UTC, JavierLeon9966 commented
Done

2022-02-23 13:04 UTC, KygekDev commented
@JavierLeon9966 Let me know if you want me to try fix the issues instead.

2022-02-25 09:13 UTC, KygekDev commented
This guy isn't responding, I think he's busy with his personal life and his server. I can't wait much longer, so I guess I'm going to try fix the issues tomorrow (in my time zone). Hopefully I can get the plugin updated on Poggit ASAP!

NB: If JavierLeon9966 reads this comment, I hope he can give a response.

2022-02-27 15:44 UTC, JavierLeon9966 commented
Sorry for not responding, you mean the issues at the issue tracker?

2022-02-27 15:49 UTC, KygekDev commented
> Sorry for not responding, you mean the issues at the issue tracker? Or the one I told you about the `int|string` type hint? Because I already fixed that

The issues I meant are the problems that needs to be addressed in this issue, including the last review I made a week ago.

2022-02-27 16:08 UTC, JavierLeon9966 commented
There are no lints in the latest build ([here](https://poggit.pmmp.io/ci/KygekTeam/KygekEatHeal/~/pr:7))

2022-02-27 16:09 UTC, KygekDev commented
> There are no lints in the latest build ([here](https://poggit.pmmp.io/ci/KygekTeam/KygekEatHeal/~/pr:7))

Okay, but could you read and comment to the review I started above?

This one:
![image](https://user-images.githubusercontent.com/68368066/155890101-04ea3900-4821-4d80-82fc-9648289cbc0c.png)

2022-02-27 16:28 UTC, JavierLeon9966 commented
You didn't send that yet, as you can see is still in pending

2022-02-27 16:29 UTC, KygekDev requested changes
Please fix the issue below.

2022-02-27 16:30 UTC, KygekDev commented on src/KygekTeam/KygekEatHeal/EatHeal.php
> -        return $price;
@JavierLeon9966 it's here now, thanks for letting me know.

2022-02-27 16:34 UTC, JavierLeon9966 commented on src/KygekTeam/KygekEatHeal/EatHeal.php
> -        return $price;
You are right, I forgot about that part. I'm gonna fix it soon

2022-02-27 16:35 UTC, KygekDev commented on src/KygekTeam/KygekEatHeal/EatHeal.php
> -        return $price;
Thanks, I'm waiting.

2022-02-27 17:22 UTC, JavierLeon9966 commented on src/KygekTeam/KygekEatHeal/EatHeal.php
> -        return $price;
Fixed

2022-03-07 05:14 UTC, JavierLeon9966 commented
Is everything done now?

2022-03-07 07:49 UTC, KygekDev commented
> Is everything done now?

I haven't tested the plugin, but I'll try to do it this week, especially because I'm no longer very busy.

2022-04-26 12:17 UTC, AIPTU approved these changes

2022-05-15 13:33 UTC, merged

2022-05-15 15:08 UTC, KygekDev commented
I haven't tested it yet, so hopefully it works...

2022-05-15 15:34 UTC, MintoD commented
> I haven't tested it yet, so hopefully it works...

Don't worry, I merged it and then I will check codes, next I'll upgrade it